---
- name: Create EC2 instances
  community.aws.ec2_instance:
    validate_certs: false
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    wait: yes
    tags:
      Name: '{{ instance_name }}'
      Owner: Jonathan Cowling
    network:
      assign_public_ip: yes
      subnet_id: "{{ first_subnet }}"
    security_group: "{{ instance_name }}-sg"
  register: ec2

- name: ensure the ec2 hosts are added to inventory
  meta: refresh_inventory
