---
# tasks file for create-ec2-instances
- name: Create piemdb-testing in default VPC
  block:
    - import_tasks: key-pair.yml
    - import_tasks: network-information.yml
    - import_tasks: security-group.yml
    - import_tasks: ec2.yml
    - meta: refresh_inventory
    - pause:
        seconds: 120
