org: Infinipie.Works
app: PieMDB
service: ${self:app}-index-builder
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'test'}
  runtime: nodejs12.x
  environment:
    ENDPOINT: ${env:ENPOINT, 'https://{service}.{region}.amazonaws.com'}
    REGION: ${env:REGION, 'eu-west-2'}
    NODE_ENV: ${self:provider.stage}
    BUCKET_NAME: piemdb-search-index-bucket-${self:provider.stage}
  region: ${self:provider.environment.REGION}
  deploymentBucket:
    name: ${self:custom.sharedBucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - 'arn:aws:dynamodb:eu-west-2:455073406672:table/PieMDB-database-${self:provider.stage}'
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - 'arn:aws:s3:::piemdb-search-index-bucket-${self:provider.stage}'
    - Effect: Allow
      Action:
        - s3:*Object
      Resource:
        - 'arn:aws:s3:::piemdb-search-index-bucket-${self:provider.stage}/*'

custom:
  basename: ${self:service}-${self:provider.stage}
  sharedBucketName: ${output:${self:app}-shared-bucket-artifacts.S3SharedBucketArtifactsName}

functions:
  piemdb-index-builder:
    handler: handler.handle
    memorySize: 256
    events:
      - schedule: rate(10 minutes)

resources:
  Resources:
    SiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
