service: piemdb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}" # allows {} inside ${}
  stage: ${{opt:stage, 'test'}}
  region: ${{env:REGION, 'eu-west-2'}}
  httpApi:
    cors: true
  deploymentBucket:
    name: ${{self:custom.sharedBucketName}}
  environment:
    NODE_ENV: ${{self:provider.stage}}
    REGION: ${{self:provider.region}}
    ENDPOINT: ${{env:ENDPOINT, https://{service}.{region}.amazonaws.com'}}
    RECAPTCHA_KEY: ${{env:RECAPTCHA_KEY, 'recaptcha-not-set'}}
    INDEX_BUCKET_NAME: piemdb-search-index-bucket-${{self:provider.stage}}
    TABLE_NAME: PieMDB-database-${{self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - 'arn:aws:dynamodb:eu-west-2:455073406672:table/${{self:provider.environment.TABLE_NAME}}'
        - 'arn:aws:dynamodb:eu-west-2:455073406672:table/${{self:provider.environment.TABLE_NAME}}/index/find-by-week'
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - 'arn:aws:s3:::${{self:provider.environment.INDEX_BUCKET_NAME}}'
    - Effect: Allow
      Action:
        - s3:*Object
      Resource:
        - 'arn:aws:s3:::${{self:provider.environment.INDEX_BUCKET_NAME}}/*'

functions:
  piemdb-app-api:
    handler: lambda.app_api
    memorySize: 128
    events:
      - httpApi:
          path: /{any+}
          method: '*'

plugins:
  - serverless-domain-manager
  - serverless-s3-sync

custom:
  sharedBucketName: ${{cf:piemdb-shared-bucket-artifacts-${{self:provider.stage}}.S3SharedBucketArtifactsName}}
  customDomain:
    domainName: piemdb-app-api-${{self:provider.stage}}.infinipie.works
    apiType: http
    endpointType: regional
    autoDomain: true
  s3Sync:
    - bucketName: piemdb.infinipie.works-${{self:provider.stage}}
      localDir: ../app/dist
      acl: public-read 

resources:
  Resources:
    SiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: piemdb.infinipie.works-${{self:provider.stage}}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET]
              AllowedOrigins: ['*']
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
