---
- hosts: local

  tasks: 
    - name: Terminate Instances
      ec2_instance_facts:
        filters: 
          "tag:Name": "{{ instance_name }}"
      register: ec2_info

    - name: displaying output  
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"

    - name: terminate an instance by tag name
      ec2: 
        instance_ids: "{{item.instance_id}}"
        state: absent
        wait: yes
      with_items: "{{ec2_info.instances}}"
