name: piemdb-deploy
on: 
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  deploy-deployment-bucket:
      if: github.event.base_ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
        
      - name: Build resources
        working-directory: academy-2020-piemdb/resources
        run: npm install

      - name: deploy bucket
        working-directory: academy-2020-piemdb/resources/s3
        run: REGION='eu-west-2' npx serverless deploy --stage test

  deploy-app-and-api:
      needs: deploy-deployment-bucket
      if: github.event.base_ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Build app-api
        working-directory: academy-2020-piemdb/app-api
        run: npm install 
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: build app
        working-directory: academy-2020-piemdb/app
        run: npm run build-test
        
      - name: deploy api and app to AWS
        working-directory: academy-2020-piemdb/app-api
        env: 
          RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY }} 
        run: REGION='eu-west-2' ENDPOINT='https://{service}.{region}.amazonaws.com' npx serverless deploy --stage test

      - name: build index-builder
        working-directory: academy-2020-piemdb/index-builder
        run: npm install

      - name: deploy index-builder to AWS
        working-directory: academy-2020-piemdb/index-builder
        run: REGION='eu-west-2' ENDPOINT='https://{service}.{region}.amazonaws.com' npx serverless deploy --stage test

  deploy-database:
      needs: deploy-deployment-bucket
      if: github.event.base_ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: install dependencies
        working-directory: academy-2020-piemdb/serverless-database
        run: npm install 
      
      - name: deploy to dynamo
        working-directory: academy-2020-piemdb/serverless-database
        run: REGION='eu-west-2' npx serverless deploy --stage test
