name: gatling-code-quality
on: 
  push: 
    paths: 
      - gatling/** 
jobs:
  gatling-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        working-directory: gatling
        run: mvn test-compile

      - name: scalastyle
        working-directory: gatling
        run: mvn scalastyle:check
      
      - name: scalafix
        working-directory: gatling
        run: mvn scalafix:scalafix
        